theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: futurs-lejeu.fr
  breadcrumb:
    position: after-hero
  search:
    active: false
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logo.svg"
  posts:
    default_image: true
    index:
      layout: grid
      show_categories: false
